-- ============================================================================
-- Orbit Outfitters sample schema — tables
-- Oracle APEX 26.1: The Complete Guide, Chapter 12
-- Run as the ORBIT schema (SQL Workshop > SQL Scripts, SQLcl, or SQL Developer).
-- Requires Oracle AI Database 26ai (BOOLEAN columns). For 19c, see the note in
-- Chapter 12 and use 01_tables_19c.sql instead.
-- ============================================================================

create table orb_categories (
    category_id         number generated by default on null as identity
                        constraint orb_categories_pk primary key,
    parent_category_id  number
                        constraint orb_categories_parent_fk
                        references orb_categories (category_id),
    category_name       varchar2(100 char) not null
                        constraint orb_categories_name_uk unique,
    description         varchar2(400 char),
    display_order       number(3)
);

create table orb_suppliers (
    supplier_id     number generated by default on null as identity
                    constraint orb_suppliers_pk primary key,
    supplier_name   varchar2(100 char) not null
                    constraint orb_suppliers_name_uk unique,
    contact_name    varchar2(100 char),
    email           varchar2(255 char),
    phone           varchar2(30 char),
    city            varchar2(60 char),
    country_code    varchar2(2 char) not null,
    is_active       boolean default true not null
);

create table orb_warehouses (
    warehouse_id    number generated by default on null as identity
                    constraint orb_warehouses_pk primary key,
    warehouse_name  varchar2(60 char) not null
                    constraint orb_warehouses_name_uk unique,
    city            varchar2(60 char) not null,
    state_province  varchar2(60 char),
    country_code    varchar2(2 char) not null,
    latitude        number(9,6),
    longitude       number(9,6)
);

create table orb_employees (
    employee_id     number generated by default on null as identity
                    constraint orb_employees_pk primary key,
    first_name      varchar2(50 char) not null,
    last_name       varchar2(50 char) not null,
    email           varchar2(255 char) not null
                    constraint orb_employees_email_uk unique,
    username        varchar2(60 char) not null
                    constraint orb_employees_username_uk unique,
    job_title       varchar2(60 char) not null,
    manager_id      number
                    constraint orb_employees_manager_fk
                    references orb_employees (employee_id),
    region          varchar2(30 char),
    hire_date       date not null,
    commission_pct  number(4,2),
    employee_name   varchar2(101 char)
                    generated always as (first_name || ' ' || last_name) virtual
);

create table orb_customers (
    customer_id     number generated by default on null as identity
                    constraint orb_customers_pk primary key,
    customer_type   varchar2(10 char) default 'RETAIL' not null
                    constraint orb_customers_type_ck
                    check (customer_type in ('RETAIL', 'WHOLESALE')),
    first_name      varchar2(50 char),
    last_name       varchar2(50 char),
    company_name    varchar2(100 char),
    email           varchar2(255 char) not null
                    constraint orb_customers_email_uk unique,
    phone           varchar2(30 char),
    address_line1   varchar2(100 char),
    city            varchar2(60 char),
    state_province  varchar2(60 char),
    postal_code     varchar2(20 char),
    country_code    varchar2(2 char) default 'US' not null,
    latitude        number(9,6),
    longitude       number(9,6),
    credit_limit    number(10,2) default 0 not null,
    loyalty_tier    varchar2(10 char) default 'BRONZE' not null
                    constraint orb_customers_tier_ck
                    check (loyalty_tier in ('BRONZE', 'SILVER', 'GOLD', 'PLATINUM')),
    sales_rep_id    number
                    constraint orb_customers_rep_fk
                    references orb_employees (employee_id),
    notes           varchar2(4000 char),
    customer_name   varchar2(101 char)
                    generated always as (
                        coalesce(company_name, first_name || ' ' || last_name)
                    ) virtual,
    created_on      date default sysdate not null,
    created_by      varchar2(255 char),
    updated_on      date,
    updated_by      varchar2(255 char),
    constraint orb_customers_name_ck
        check (company_name is not null or last_name is not null)
);

create table orb_products (
    product_id        number generated by default on null as identity
                      constraint orb_products_pk primary key,
    sku               varchar2(20 char) not null
                      constraint orb_products_sku_uk unique,
    product_name      varchar2(100 char) not null,
    category_id       number not null
                      constraint orb_products_category_fk
                      references orb_categories (category_id),
    supplier_id       number
                      constraint orb_products_supplier_fk
                      references orb_suppliers (supplier_id),
    description       varchar2(4000 char),
    unit_price        number(10,2) not null
                      constraint orb_products_price_ck check (unit_price >= 0),
    cost_price        number(10,2),
    reorder_level     number(6) default 20 not null,
    weight_kg         number(6,2),
    color             varchar2(30 char),
    launch_date       date,
    is_active         boolean default true not null,
    product_image     blob,
    image_mime_type   varchar2(255 char),
    image_filename    varchar2(400 char),
    image_updated_on  date,
    created_on        date default sysdate not null,
    created_by        varchar2(255 char),
    updated_on        date,
    updated_by        varchar2(255 char)
);

create index orb_products_category_ix on orb_products (category_id);
create index orb_products_supplier_ix on orb_products (supplier_id);

create table orb_inventory (
    inventory_id      number generated by default on null as identity
                      constraint orb_inventory_pk primary key,
    product_id        number not null
                      constraint orb_inventory_product_fk
                      references orb_products (product_id) on delete cascade,
    warehouse_id      number not null
                      constraint orb_inventory_warehouse_fk
                      references orb_warehouses (warehouse_id),
    quantity_on_hand  number(8) default 0 not null
                      constraint orb_inventory_qty_ck check (quantity_on_hand >= 0),
    last_counted_on   date,
    constraint orb_inventory_uk unique (product_id, warehouse_id)
);

create index orb_inventory_warehouse_ix on orb_inventory (warehouse_id);

create table orb_orders (
    order_id        number generated by default on null as identity
                    constraint orb_orders_pk primary key,
    order_number    varchar2(20 char) not null
                    constraint orb_orders_number_uk unique,
    customer_id     number not null
                    constraint orb_orders_customer_fk
                    references orb_customers (customer_id),
    sales_rep_id    number
                    constraint orb_orders_rep_fk
                    references orb_employees (employee_id),
    warehouse_id    number
                    constraint orb_orders_warehouse_fk
                    references orb_warehouses (warehouse_id),
    order_date      date default trunc(sysdate) not null,
    required_date   date,
    shipped_date    date,
    status          varchar2(20 char) default 'NEW' not null
                    constraint orb_orders_status_ck
                    check (status in ('NEW', 'PENDING_APPROVAL', 'APPROVED',
                                      'SHIPPED', 'DELIVERED', 'CANCELLED')),
    channel         varchar2(20 char) default 'STORE' not null
                    constraint orb_orders_channel_ck
                    check (channel in ('STORE', 'ONLINE', 'PHONE', 'SALES_REP')),
    payment_method  varchar2(20 char)
                    constraint orb_orders_payment_ck
                    check (payment_method in ('CARD', 'CASH', 'BANK_TRANSFER', 'INVOICE')),
    discount_pct    number(5,2) default 0 not null
                    constraint orb_orders_discount_ck
                    check (discount_pct between 0 and 50),
    order_total     number(12,2) default 0 not null,
    notes           varchar2(4000 char),
    created_on      date default sysdate not null,
    created_by      varchar2(255 char),
    updated_on      date,
    updated_by      varchar2(255 char)
);

create index orb_orders_customer_ix on orb_orders (customer_id);
create index orb_orders_rep_ix on orb_orders (sales_rep_id);
create index orb_orders_warehouse_ix on orb_orders (warehouse_id);
create index orb_orders_date_ix on orb_orders (order_date);

create table orb_order_items (
    order_item_id   number generated by default on null as identity
                    constraint orb_order_items_pk primary key,
    order_id        number not null
                    constraint orb_order_items_order_fk
                    references orb_orders (order_id) on delete cascade,
    line_no         number(4) not null,
    product_id      number not null
                    constraint orb_order_items_product_fk
                    references orb_products (product_id),
    quantity        number(6) not null
                    constraint orb_order_items_qty_ck check (quantity > 0),
    unit_price      number(10,2) not null,
    discount_pct    number(5,2) default 0 not null,
    line_total      number(12,2)
                    generated always as (
                        round(quantity * unit_price * (1 - discount_pct / 100), 2)
                    ) virtual,
    constraint orb_order_items_uk unique (order_id, line_no)
);

create index orb_order_items_product_ix on orb_order_items (product_id);

create table orb_promotions (
    promotion_id    number generated by default on null as identity
                    constraint orb_promotions_pk primary key,
    promotion_name  varchar2(100 char) not null,
    category_id     number
                    constraint orb_promotions_category_fk
                    references orb_categories (category_id),
    start_date      date not null,
    end_date        date not null,
    discount_pct    number(5,2) not null,
    description     varchar2(1000 char),
    constraint orb_promotions_dates_ck check (end_date >= start_date)
);

create table orb_product_reviews (
    review_id       number generated by default on null as identity
                    constraint orb_product_reviews_pk primary key,
    product_id      number not null
                    constraint orb_reviews_product_fk
                    references orb_products (product_id) on delete cascade,
    customer_id     number
                    constraint orb_reviews_customer_fk
                    references orb_customers (customer_id),
    rating          number(1) not null
                    constraint orb_reviews_rating_ck check (rating between 1 and 5),
    review_title    varchar2(200 char),
    review_text     varchar2(4000 char),
    review_date     date default trunc(sysdate) not null
);

create index orb_reviews_product_ix on orb_product_reviews (product_id);

comment on table orb_customers is 'Retail and wholesale customers of Orbit Outfitters';
comment on table orb_products is 'The product catalog';
comment on table orb_orders is 'Order headers; ORDER_TOTAL is maintained by a trigger on ORB_ORDER_ITEMS';
comment on table orb_order_items is 'Order lines';
comment on column orb_orders.status is 'NEW, PENDING_APPROVAL, APPROVED, SHIPPED, DELIVERED or CANCELLED';
comment on column orb_products.reorder_level is 'Stock level at or below which the product should be reordered';
