-- ============================================================================
-- ORB_STORES: the retail stores table that Chapter 11 loads from orbit-stores.csv
-- with Data Workshop. Run this script instead if you skipped that exercise.
-- ============================================================================
create table orb_stores (
    id               number generated by default on null as identity
                     constraint orb_stores_pk primary key,
    store_name       varchar2(100),
    city             varchar2(50),
    state            varchar2(50),
    country          varchar2(50),
    opened_on        date,
    latitude         number,
    longitude        number,
    floor_area_sqft  number,
    flagship         boolean
);

insert into orb_stores (store_name, city, state, country, opened_on, latitude, longitude, floor_area_sqft, flagship)
values ('Orbit Denver Union Station', 'Denver', 'Colorado', 'US', date '2016-04-15', 39.7527, -105.0003, 12500, true);
insert into orb_stores (store_name, city, state, country, opened_on, latitude, longitude, floor_area_sqft, flagship)
values ('Orbit Boulder Pearl Street', 'Boulder', 'Colorado', 'US', date '2018-09-01', 40.0182, -105.2778, 6400, false);
insert into orb_stores (store_name, city, state, country, opened_on, latitude, longitude, floor_area_sqft, flagship)
values ('Orbit Seattle Capitol Hill', 'Seattle', 'Washington', 'US', date '2017-03-20', 47.6231, -122.3208, 9800, true);
insert into orb_stores (store_name, city, state, country, opened_on, latitude, longitude, floor_area_sqft, flagship)
values ('Orbit Portland Pearl District', 'Portland', 'Oregon', 'US', date '2019-05-11', 45.5270, -122.6819, 7200, false);
insert into orb_stores (store_name, city, state, country, opened_on, latitude, longitude, floor_area_sqft, flagship)
values ('Orbit San Francisco Mission', 'San Francisco', 'California', 'US', date '2020-02-07', 37.7599, -122.4148, 8100, false);
insert into orb_stores (store_name, city, state, country, opened_on, latitude, longitude, floor_area_sqft, flagship)
values ('Orbit Salt Lake City Downtown', 'Salt Lake City', 'Utah', 'US', date '2021-06-18', 40.7596, -111.8868, 6900, false);
insert into orb_stores (store_name, city, state, country, opened_on, latitude, longitude, floor_area_sqft, flagship)
values ('Orbit Chicago River North', 'Chicago', 'Illinois', 'US', date '2018-11-03', 41.8924, -87.6341, 11200, true);
insert into orb_stores (store_name, city, state, country, opened_on, latitude, longitude, floor_area_sqft, flagship)
values ('Orbit Minneapolis North Loop', 'Minneapolis', 'Minnesota', 'US', date '2022-04-22', 44.9883, -93.2733, 5800, false);
insert into orb_stores (store_name, city, state, country, opened_on, latitude, longitude, floor_area_sqft, flagship)
values ('Orbit Atlanta Ponce City', 'Atlanta', 'Georgia', 'US', date '2019-10-12', 33.7726, -84.3656, 8600, false);
insert into orb_stores (store_name, city, state, country, opened_on, latitude, longitude, floor_area_sqft, flagship)
values ('Orbit Boston Back Bay', 'Boston', 'Massachusetts', 'US', date '2020-08-29', 42.3505, -71.0810, 7700, false);
insert into orb_stores (store_name, city, state, country, opened_on, latitude, longitude, floor_area_sqft, flagship)
values ('Orbit Asheville Downtown', 'Asheville', 'North Carolina', 'US', date '2023-03-04', 35.5946, -82.5540, 4900, false);
insert into orb_stores (store_name, city, state, country, opened_on, latitude, longitude, floor_area_sqft, flagship)
values ('Orbit Toronto Queen West', 'Toronto', 'Ontario', 'CA', date '2021-09-17', 43.6477, -79.4020, 9300, true);
commit;
