-- Installs the Orbit Outfitters sample schema. Run as ORBIT:
--   sql orbit@localhost:1521/FREEPDB1 @install.sql
set define off
prompt Creating tables...
@@01_tables.sql
prompt Creating triggers, package, and views...
@@02_logic.sql
prompt Loading sample data (about a minute)...
@@03_data.sql
prompt Creating application users and password checking (Chapter 35; needs execute on sys.dbms_crypto)...
@@06_auth.sql
prompt Creating the order duality view (Chapter 40)...
@@07_duality.sql
prompt Orbit Outfitters sample schema installed.
